[project]
name = "llamaindex-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "llama-index>=0.13.0",
    "llama-index-llms-dashscope>=0.5.0",
    "llama-index-llms-openai-like>=0.5.0",
]
