transfer_task:
  description: |
    处理用户的转账请求，包括信息收集、验证和执行转账操作。
    
    任务步骤：
    1. 分析用户的转账需求
    2. 查询相关账户信息
    3. 验证转账信息的有效性
    4. 当信息不足时，向用户提问获取更多信息
    5. 与用户确认转账详情
    6. 执行转账操作
    7. 返回转账结果
    
    特殊情况处理：
    - 如果目标账户不存在，询问用户正确的账户信息
    - 如果余额不足，询问用户是否要调整转账金额
    - 如果转账金额不明确，询问用户具体的转账金额
    
    输入信息：
    - user_request: 用户的转账请求
    
    输出要求：
    - 转账结果报告，包含：
      * 转账是否成功
      * 转账金额
      * 目标账户
      * 转账ID（如果成功）
      * 错误信息（如果失败）
      * 用户交互过程（如果有提问）
    
  expected_output: |
    详细的转账处理报告，包含所有相关信息和结果，以及用户交互过程。
    
  agent: transfer_agent 